### ISSUE TITLE
Error raises in Term-Counter.py

### ISSUE THREAD

**Issue by christmoore** [MrMepper/TwitterDataMiner#1]
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.5.1\helpers\pydev\pydevd.py", line 2357, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.5.1\helpers\pydev\pydevd.py", line 1777, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.5.1\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "C:/Users/Chris/PycharmProjects/TwitterDataMiner/Term-Counter.py", line 15, in <module>
    tweet = json.loads(line)
  File "C:\Python34\lib\json__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 2 column 1 (char 1)

Error is raised when an empty line in the "python.json" file is hit.

**Comment by christmoore** [comment]
Issue addressed. Removed empty lines from python.json.
